config/routes.rb
Rails.application.routes.draw do
  
  get 'welcome/index'
  get 'welcome/login'
  get 'dashboard/index'
  get 'welcome/index'
  
  resources :images
  resources :schedules
  resources :users
  resources :announcements
  
  root 'welcome#index'
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'sessions', to: redirect('/')
  get 'show', to: 'images#show'

  
  #change images to welcome
  root 'welcome#base'
  

end

app/models/announcement.rb
class Announcement < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
    #attr_accessible :title, :caption, :img
    has_one_attached :picture
    mount_uploader :img, ImgUploader
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
    def new
        @announcement = Announcement.new
    end
    def show
        @announcement = Announcement.find(params[:id])
    end 
    def create
        @announcement = Announcement.new(article_params)
       
        if @announcement.save
  
            redirect_to @announcement
        else
        render 'new'
        end
    end
    def edit
        @announcement = Announcement.find(params[:id])
    end
    def update
        @announcement = Announcement.find(params[:id])
        if @announcement.update(article_params)
            redirect_to @announcement
        else
            render 'edit'
        end
    end
    def destroy
        @announcement = Announcement.find(params[:id])
        @announcement.destroy
        redirect_to announcements_path
    end
    def index 
        @announcement = Announcement.all
    end 
end

private
    def article_params
       params.require(:announcement).permit(:title, :text)
    end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end
  
  def authorize_admin
    if session[:user_id]
    redirect_back fallback_location: root_path, status: 401 unless current_user.admin
    flash[:notice] = 'Only admins can view that page' unless current_user.admin
    else 
    redirect_back fallback_location: root_path, status: 401
    flash[:notice] = "Unknown Error Occurred"
    end 
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
   # @images = Image.last(2)
  end
  
 
  
   def new
    @image = Image.new
   end
  
  def form
   
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show

    @image = Image.find(params[:id])

  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:title, :caption, :img)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if check_login 
      redirect_to 'dashboards/form'
    end
  end

  def create
    
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now[:alert] = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
  
  def check_login 
    return session[:user_id]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authorize_admin, only: :index

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :admin)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @images = Image.last(2)
    @announcement = Announcement.last(2)
  end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/type_of_user_helper.rb
module TypeOfUserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/announcements/_form.html.erb
<%= form_for @announcement do |f| %>
 
  <% if @announcement.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@announcement.errors.count, "error") %> prohibited
        this announcement from being saved:
      </h2>
      <ul>
        <% @announcement.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/announcements/edit.html.erb
<h1>Editing announcement</h1>
 
<%= render 'form' %>

<%= link_to 'Back', announcements_path %>
    

app/views/announcements/index.html.erb
<div class="container-fluid text-center">
<h1 class="shift">Announcement List</h1>
<%= link_to 'New announcement', new_announcement_path %><br><br>
<table class="shifts">
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
     
  <% @announcement.each do |announcement| %>
    <tr>
      <td><%= announcement.title %></td>
      
      <td><%= announcement.text %></td>
      
      
      <td><button><%= link_to 'Show', announcement_path(announcement) %></button><br></td>
       
      <% if current_user.admin %>
      
      <td><button><%= link_to 'Edit', edit_announcement_path(announcement) %></button></td>
      <td><button><%= link_to 'Delete',
      announcement_path(announcement),
      method: :delete,
      data: { confirm: 'Are you sure?' } %></button></td>
      <%end%>
    </tr>
  <% end %>
</table>

<br>
<button><%= link_to 'Dashboard', welcome_index_path %></button>
</div>

app/views/announcements/new.html.erb
<div class="container-fluid text-center">
<div>
<h1 class="shift">New Announcement</h1><br>
<%= render 'form' %>

<button><%= link_to 'Back', announcements_path %></button>
<button><%= link_to 'Dashboard', welcome_index_path %></button>
</div>
</div>

app/views/announcements/show.html.erb
<h1>Announcements</h1>
<p>
    <strong>Title</strong>
    <%=@announcement.title%>
</p>
<p>
    <strong>Title</strong>
    <%=@announcement.text%>
</p>
<button><%= link_to 'Announcements List', announcements_path %></button>
<button><%= link_to 'Dashboard', welcome_index_path %></button>

app/views/dashboard/_form.html.erb
<div class="container-fluid text-center">
   <h2 class = "float-left"> My Dashboard </h2>

<div class="margin" >
  <div class="row">

     <div class="col-sm-4">   
     <%= image_tag("Lookoutsche.jpg", :alt => "Schedule", class: "resize3") %>
     </div>
     
     
        
      <div class="col-sm-8">
        <h1>This weeks schedule</h1> 
        <% if @images[0]!=nil %>
        <br>
        <%= image_tag(@images[0].img_url.to_s) %> <br>
        <% end %>
        
        
        
        <% if current_user.admin %>
        
        <br><br>
    
        <button class="button_dec"><span> <%=link_to'Upload Schedule', new_image_path, class: "button_dec"%></span></button>
     
        <button class="button_dec"><%= link_to 'Delete Schedule', @images[0], method: :delete, data: { confirm: 'Are you sure?' }, class: "button_dec"%></button>
        <button class="button_dec"><%= link_to 'Previous Schedules', images_path, class:"button_dec" %></button>
        <% else %>
        <br>
        <button><%= link_to 'Previous Schedules', images_path %></button>
        
        <% end %>
        
    </div>
 </div>

  
  
    <div class="row">
        <div class="col-sm-4">
            <%= image_tag("announcement.png", :alt => "announcment", class: "resize2") %>
        </div>
        
        <div class="col-sm-8">
           <h1>Announcements</h1> 
           <% if @announcement[0]!=nil %>
        <br>
        <strong> <%= @announcement[0].title %></strong><br><br>
        <div class="txt">
           
                 <%= @announcement[0].text %> <br>
           <% end %>
           
        </div>
           <br>
            <% if current_user.admin %>
            <button class="button_dec"><span> <%=link_to'Post Announcement', new_announcement_path, class:"button_dec" %></span></button>
            <button class="button_dec"><%= link_to 'Delete Announcement', @announcement[0], method: :delete, data: { confirm: 'Are you sure?' }, class:"button_dec" %></button>
            
            <% end %>
        </div>
        
                 
           
    </div>
     
    </div>
</div>

app/views/images/_form.html.erb
<%= form_for @image, :html => {:multipart => true} do |form| %>
<div class="pic">
  <div class="backpic">
  </div>

</div>
  <% if image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div text-align: center %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="field">
    <%= form.label :img %>
   <%= form.file_field :img %> 
  </div>
  <div class="field">
    <%= form.label :caption %>
    <%= form.text_area :caption %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing Schedule</h1>

<%= render 'form', image: @image %>

<%= link_to 'Show Schedule', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
  
<p id="notice"><%= notice %></p>
<div class="pic">
  <div class="backpic">
  </div>
</div>


<h1 class="shiftss">Schedules</h1>

<table class="shifts">
  <thead>
    <tr>
      <th>Title</th>
      <th>Caption</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.title %></td>
        <td><%= image.caption %></td>
       <td><%= link_to 'Show', image %></td>
        <% if current_user.admin %>
       <td><%= link_to 'Edit', edit_image_path(image) %></td>
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
  
  
</table>
<button class="shifts"><%= link_to 'Dashboard', welcome_index_path %></button>

app/views/images/new.html.erb
<div class="container-fluid text-center">
<h1 class="shift">New Schedule</h1>

<%= render 'form', image: @image %><br>


<button><%= link_to 'Dashboard', welcome_index_path %></button>
</div>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @image.title %>
</p>




  <%= image_tag(@image.img_url.to_s) %>



<p>
  <strong>Caption:</strong>
  <%= @image.caption %>
</p>
<% if current_user.admin %>
<%= link_to 'Edit', edit_image_path(@image) %> |
<%end%>
<%= link_to 'Back', welcome_index_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lookout</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-color:#ebebe0;">
    <div class = "float-right">
     <% if current_user %>
         Logged in as <%= current_user.email %>. 
         <button onclick="window.location.href='/logout'">Logout</button>
        <% end %>
    </div>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
  </body>
  <footer>
    
  </footer>
</html>

app/views/schedules/new.html.erb
<div class ="container-fluid text-center">
<h1>Add New Schedule</h1>

def new
        @schedule = Schedule.new
    end
    def show
        @schedule = Schedule.find(params[:id])
    end 
    def create
        @schedule = Schedule.new(schedule_params)
        byebug
        if @schedule.save
            byebug
            redirect_to @schedule
        else
        render 'new'
        end
    end
    def edit
        @schedule = Schedule.find(params[:id])
    end
    def update
        @schedule = Schedule.find(params[:id])
        if @schedule.update(schedule_params)
            redirect_to @schedule
        else
            render 'edit'
        end
    end
    def destroy
        @schedule = Schedule.find(params[:id])
        @schedule.destroy
        redirect_to schedules_path
    end
    def index 
        @schedule = Schedule.all
    end 
end

private
    def schedules_params
       params.require(:schedule).permit(:title, :text)
    end
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field"><br>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field"><br>
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>
  
 <br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="pic">

</div>
  
<p id="notice"><%= notice %></p>

<div class = "float-right">

<% if current_user %>
  Logged in as <%= current_user.email %>. 
  <button onclick="window.location.href='/logout'">Logout</button>
   <% end %>
   
</div>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="container-fluid text-center">
<div class="bord">
<h1>New User</h1><br>
  
<%= render 'form', user: @user %>

<%= link_to 'Back', welcome_index_path %>

</div>

</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back',  welcome_index_path %>

app/views/welcome/_home.html.erb
<div class="container-fluid text-center">

<div class="pic">
  
  </div>

<div>
    
    <div>
        
    <div id="demo" class="carousel slide background" data-ride="carousel">

  <!-- Indicators -->
  <ul class="carousel-indicators">
    <li data-target="#demo" data-slide-to="0" class="active"></li>
    <li data-target="#demo" data-slide-to="1"></li>
    <li data-target="#demo" data-slide-to="2"></li>
  </ul>

  <!-- The slideshow -->
  <div class="carousel-inner">
    
    <div class="carousel-item active">
         <div class="row">
          <div class="col-sm-6 cen">
            
              <h1 class="orange"> Lookout </h1>
              <h3 class="white"> Work Scheduling Made Simple.</h3>
            
          </div>
          
          <div class="col-sm-6">
              <%= image_tag("carasel 1.jpg", :alt => "Happy people", class: "resize") %>
          </div>
        
        
       
        </div>
    </div>
    
    
    
    <div class="carousel-item">
      <div class="row">
       
          <div class="col-sm-6 cen">
             <h3 class="text-center white"> Make announcements  </h3>
          </div>
          
          <div class="col-sm-6"> 
          <%= image_tag("caresel 4.jpg", :alt => "Happy people", class: "resize") %> 
          </div>
        
          
      
        </div>
    </div>
    
    
    <div class="carousel-item">
       <div class="row">
          <div class="col-sm-6"> 
          <%= image_tag("caresel 5.jpg", :alt => "Happy people", class: "resize") %> 
          </div>
        
          <div class="col-sm-6 cen">
             <h3 class="text-center white"> Upload schedules </h3>
             </div>
      
        </div>
           
    </div>
    
    </div>
  

  <!-- Left and right controls -->
  <a class="carousel-control-prev" href="#demo" data-slide="prev">
    <span class="carousel-control-prev-icon"></span>
  </a>
  <a class="carousel-control-next" href="#demo" data-slide="next">
    <span class="carousel-control-next-icon"></span>
  </a>

</div>

<br><br>
  <div>
  
       <button class = "Button-edit" type="Sign Up"> <span><%= link_to"Sign Up", signup_path, class: "link_dec" %></span></button><br><br>
       <button class = "Button-edit" type="Login"> <span><%= link_to"Login", login_path, class: "link_dec" %></span></button><br><br>
    </div>



   
   
    
  
       
   </div>

</div>

app/views/welcome/base.html.erb
<div class="container-fluid text-center">

   <div class="pic">
  <div class="backpic">
  </div>

</div>
<h1>Lookout</h1>

   <h2>Work Scheduling Made Simple.</h2><br><br>


<button class = "Button-edit" type="Admin"> <span><%= link_to"Admin", welcome_index_path, class: "link_dec" %></span></button><br><br>

<button class = "Button-edit" type="Employee"> <span><%= link_to"Employee", images_path, class: "link_dec" %></span></button><br><br>

</div>

app/views/welcome/index.html.erb
<div class="container-fluid text-center">

   <div class="pic">
  
  
</div>




<div>
 <% if current_user %>
   <%= render 'dashboard/form' %>
<% else %>
  <%= render 'home' %>
<% end %>
</div>